services:
  - type: web
    name: asda-scraper-app
    runtime: docker
    plan: free
    envVars:
      - key: PORT
        value: 80
      - key: SELENIUM_HUB_URL
        value: https://my-selenium-grid-driver.onrender.com/wd/hub
      - key: REMOTE_SERVER
        value: 1
        