services:
  - type: web
    name: asda-scraper-app
    dockerfileDir: .
    envVars:
      - key: PORT
        value: 81
      - key: ENVIRONMENT
        fromService:
          type: web
          name: my-selenium-grid-driver
          property: ENVIRONMENT
    ports:
      - 81:81

  - type: web
    name: my-selenium-grid-driver
    image: seleniarm/standalone-chromium
    envVars:
      - key: ENVIRONMENT
        value: production
    ports:
      - 4444:4444
      - 7900:7900
